### ISSUE TITLE
No response using usePopup prop with appleAuthHelpers

### ISSUE THREAD

**Issue by jacqueswho** [A-Tokyo/react-apple-signin-auth#65] opened 2021-10-06 10:13 UTC
Hi

I am trying your appleAuthHelpers.signIn function. below is my code. For some strange reason I don't get an onSuccess response. 

I get the popup below

![image](https://user-images.githubusercontent.com/4375492/136183671-7003c70e-6fa7-416c-93a1-76524896a542.png)

After clicking continue nothing happens

![image](https://user-images.githubusercontent.com/4375492/136183826-7083df2e-3e5d-4b5a-8adb-4bcb79806ee8.png)

```JS

import React, { useCallback, useEffect, useRef, useState } from 'react';
import { appleAuthHelpers, useScript } from 'react-apple-signin-auth';
import {
  Alert,
  Button,
  ButtonGroup,
  ButtonGroupProps,
  Image
} from '@chakra-ui/react';
import { nanoid } from 'nanoid/non-secure';

const Social: React.FC<SocialProps> = ({ joinSession, ...rest }) => {
  const { t } = useTranslation();
  const dispatch = useDispatch();
  useScript(appleAuthHelpers.APPLE_SCRIPT_SRC);

const signInApple = useCallback(() => {
    const nonce = nanoid();
    appleAuthHelpers.signIn({
      authOptions: {
        clientId: config.apple.clientId,
        /** Requested scopes, seperated by spaces - eg: 'email name' */
        scope: 'email name',
        /** Apple's redirectURI - must be one of the URIs you added to the serviceID - the undocumented trick in apple docs is that you should call auth from a page that is listed as a redirectURI, localhost fails */
        redirectURI: config.apple.redirectUrl,
        state: 'state',
        /** Nonce */
        nonce,
        usePopup: true,
      },
      onSuccess: (response: AppleAuthResponse) => console.log(response),
      onError: (error: any) => console.error(error),
    });
  }, []);

return ( <Button
          w="100%"
          type="button"
          colorScheme="black"
          boxShadow="lg"
          leftIcon={
            <Image
              src={appleImage}
              alt="Apple"
              htmlWidth="1.22em"
              htmlHeight="auto"
              w="1.22em"
              h="auto"
              mr="2"
            />
          }
          onClick={signInApple}
        >
          {t('auth.ssoApple')}
        </Button>

)

};

export default Social;

```

**Comment by A-Tokyo** [comment] 2021-10-06 10:56
Duplicate of https://github.com/A-Tokyo/react-apple-signin-auth/issues/64

This is the default behavior from Apple Inc. You should use `state` instead.

**Closed by A-Tokyo** 2021-10-06 10:56 UTC

**Comment by jacqueswho** [comment] 2021-10-06 11:02
@A-Tokyo but usePopup is true? I don't even need the state. I just want the authorization.id_token

**Comment by jacqueswho** [comment] 2021-10-06 11:04
@A-Tokyo It does the same for me on your demo site. When you click continue, nothing happens. Should it not close and give onSuccess response?

**Comment by jacqueswho** [comment] 2021-10-06 11:45
@A-Tokyo Am I doing something wrong then?

**Comment by jacqueswho** [comment] 2021-10-06 12:13
> Duplicate of #64
> 
> This is the default behavior from Apple Inc. You should use `state` instead.

@A-Tokyo This is not a duplicate, because usePopup: true

**Comment by jacqueswho** [comment] 2021-10-06 12:20
@A-Tokyo I tried the button as well, I don't think usePopup is working?

```JS
 <AppleSignin
          /** Auth options passed to AppleID.auth.init() */
          authOptions={{
            /** Client ID - eg: 'com.example.com' */
            clientId: config.apple.clientId,
            /** Requested scopes, seperated by spaces - eg: 'email name' */
            scope: 'email name',
            /** Apple's redirectURI - must be one of the URIs you added to the serviceID - the undocumented trick in apple docs is that you should call auth from a page that is listed as a redirectURI, localhost fails */
            redirectURI: config.apple.redirectUrl,
            /** State string that is returned with the apple response */
            state: 'state',
            /** Nonce */
            nonce: nanoid(),
            /** Uses popup auth instead of redirection */
            usePopup: true,
          }} // REQUIRED
          /** General props */
          uiType="dark"
          /** className */
          className="apple-auth-btn"
          /** Removes default style tag */
          noDefaultStyle={false}
          /** Allows to change the button's children, eg: for changing the button text */
          buttonExtraChildren="Signin with Apple"
          /** Extra controlling props */
          /** Called upon signin success in case authOptions.usePopup = true -- which means auth is handled client side */
          onSuccess={onAppleSuccess} // default = undefined
          /** Called upon signin error */
          onError={onFailure} // default = undefined
          /** Skips loading the apple script if true */
          skipScript={false} // default = undefined
          /** Apple image props */
          iconProp={{ style: { marginTop: '10px' } }} // default = undefined
        />

```

**Comment by jacqueswho** [comment] 2021-10-06 14:47
@A-Tokyo my apologies, your last comment is important 'localhost fails'
`/** Apple's redirectURI - must be one of the URIs you added to the serviceID - the undocumented trick in apple docs is that you should call auth from a page that is listed as a redirectURI, localhost fails */`

**Comment by CoericK** [comment] 2022-04-30 08:20
hello @jacqueswho @A-Tokyo , im havig the same issue, https://dev.vecinos.pe/, i click continue, and nothing happens, i click it again and it shows an error ocurred message, another thing i noticed is that my reditect url is not being hit, neither, via post or get

**Comment by Alex-zzzx** [comment] 2025-08-07 07:12
> [@a-tokyo](https://github.com/a-tokyo) my apologies, your last comment is important 'localhost fails' `/** Apple's redirectURI - must be one of the URIs you added to the serviceID - the undocumented trick in apple docs is that you should call auth from a page that is listed as a redirectURI, localhost fails */`

Hello, I'm encountering the same issue. Could you please tell me how to solve it?
